CREATE TABLE PRODUCT (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE PRODUCT_DETAILS (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    BAR_CODE VARCHAR(100) NOT NULL,
    UNIT_PRICE DOUBLE NOT NULL
);

CREATE TABLE MANUFACTURER (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE CONSUMER (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CONSTRAINT U_NEWSLETTER_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE PAYMENT (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    MODE VARCHAR(100) NOT NULL,
    INSTALLMENTS VARCHAR(100) NOT NULL
);

CREATE TABLE DELIVERY (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    MODE VARCHAR (100) NOT NULL
);

CREATE TABLE "ORDER" (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    ID_CONSUMER BIGINT NOT NULL,
    ID_PAYMENT BIGINT NOT NULL,
    ID_DELIVERY BIGINT NOT NULL,
    CONSTRAINT FK_CONSUMER FOREIGN KEY (ID_CONSUMER) REFERENCES CONSUMER (ID),
    CONSTRAINT FK_PAYMENT FOREIGN KEY (ID_PAYMENT) REFERENCES PAYMENT (ID),
    CONSTRAINT FK_DELIVERY FOREIGN KEY (ID_DELIVERY) REFERENCES DELIVERY (ID)
);

CREATE TABLE PRODUCT_ORDER (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    ID_ORDER BIGINT NOT NULL,
    ID_PRODUCT BIGINT NOT NULL,
    CONSTRAINT FK_ORDER FOREIGN KEY (ID_ORDER) REFERENCES "ORDER" (ID),
    CONSTRAINT FK_PRODUCT FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT (ID)
);
